// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReunionesDeAmigos.Infrastructure.Persistence;

#nullable disable

namespace ReunionesDeAmigos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReunionesDeAmigos.Domain.Entities.Lugar", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Barrio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<decimal?>("Latitud")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("Longitud")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Ciudad", "Tipo", "Activo");

                    b.ToTable("lugares", null, t =>
                        {
                            t.HasCheckConstraint("CK_lugares_coordenadas", "(\"Latitud\" IS NULL AND \"Longitud\" IS NULL) OR (\"Latitud\" BETWEEN -90 AND 90 AND \"Longitud\" BETWEEN -180 AND 180)");
                        });
                });

            modelBuilder.Entity("ReunionesDeAmigos.Domain.Entities.ParticipanteSalida", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CredencialInvitadoHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("FechaIngreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreVisible")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SalidaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CredencialInvitadoHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.HasIndex("SalidaId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("participantes_salida", null, t =>
                        {
                            t.HasCheckConstraint("CK_participantes_salida_identidad", "(\"UsuarioId\" IS NOT NULL AND \"CredencialInvitadoHash\" IS NULL) OR (\"UsuarioId\" IS NULL AND \"CredencialInvitadoHash\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ReunionesDeAmigos.Domain.Entities.Propuesta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DescripcionManual")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DireccionManual")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LugarId")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreManual")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("ParticipanteSalidaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SalidaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LugarId");

                    b.HasIndex("ParticipanteSalidaId");

                    b.HasIndex("SalidaId", "LugarId")
                        .IsUnique();

                    b.ToTable("propuestas", null, t =>
                        {
                            t.HasCheckConstraint("CK_propuestas_tipo", "(\"Tipo\" = 1 AND \"LugarId\" IS NOT NULL AND \"NombreManual\" IS NULL) OR (\"Tipo\" = 2 AND \"LugarId\" IS NULL AND \"NombreManual\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ReunionesDeAmigos.Domain.Entities.Salida", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoAcceso")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("CreadorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("FechaCancelacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FechaEncuentro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FechaFinPropuestas")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FechaFinVotacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoAcceso")
                        .IsUnique();

                    b.HasIndex("CreadorId");

                    b.ToTable("salidas", null, t =>
                        {
                            t.HasCheckConstraint("CK_salidas_fechas", "\"FechaFinPropuestas\" < \"FechaFinVotacion\" AND \"FechaFinVotacion\" < \"FechaEncuentro\"");
                        });
                });

            modelBuilder.Entity("ReunionesDeAmigos.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ReunionesDeAmigos.Domain.Entities.Voto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FechaUltimaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ParticipanteSalidaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PropuestaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SalidaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParticipanteSalidaId");

                    b.HasIndex("PropuestaId");

                    b.HasIndex("SalidaId", "ParticipanteSalidaId")
                        .IsUnique();

                    b.ToTable("votos", (string)null);
                });

            modelBuilder.Entity("ReunionesDeAmigos.Domain.Entities.ParticipanteSalida", b =>
                {
                    b.HasOne("ReunionesDeAmigos.Domain.Entities.Salida", null)
                        .WithMany("Participantes")
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReunionesDeAmigos.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ReunionesDeAmigos.Domain.Entities.Propuesta", b =>
                {
                    b.HasOne("ReunionesDeAmigos.Domain.Entities.Lugar", null)
                        .WithMany()
                        .HasForeignKey("LugarId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ReunionesDeAmigos.Domain.Entities.ParticipanteSalida", null)
                        .WithMany()
                        .HasForeignKey("ParticipanteSalidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReunionesDeAmigos.Domain.Entities.Salida", null)
                        .WithMany("Propuestas")
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReunionesDeAmigos.Domain.Entities.Salida", b =>
                {
                    b.HasOne("ReunionesDeAmigos.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ReunionesDeAmigos.Domain.Entities.Voto", b =>
                {
                    b.HasOne("ReunionesDeAmigos.Domain.Entities.ParticipanteSalida", null)
                        .WithMany()
                        .HasForeignKey("ParticipanteSalidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReunionesDeAmigos.Domain.Entities.Propuesta", null)
                        .WithMany()
                        .HasForeignKey("PropuestaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReunionesDeAmigos.Domain.Entities.Salida", null)
                        .WithMany("Votos")
                        .HasForeignKey("SalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReunionesDeAmigos.Domain.Entities.Salida", b =>
                {
                    b.Navigation("Participantes");

                    b.Navigation("Propuestas");

                    b.Navigation("Votos");
                });
#pragma warning restore 612, 618
        }
    }
}
